from http import HTTPStatus

OK = HTTPStatus.OK
CREATED = HTTPStatus.CREATED
BAD_REQUEST = HTTPStatus.BAD_REQUEST
NOT_FOUND = HTTPStatus.NOT_FOUND
CONFLICT = HTTPStatus.CONFLICT
UNPROCESSABLE = HTTPStatus.UNPROCESSABLE_ENTITY